"""Ports. The domain talks to these, never to a storage engine."""
from __future__ import annotations
from typing import Protocol, runtime_checkable
from .models import BookRecord, LibraryQuery, WriteResult


@runtime_checkable
class LibraryRepository(Protocol):
    def capabilities(self) -> dict:
        """e.g. {"readings": "full"} or {"readings": "latest-only"}."""
        ...
    def upsert_book(self, book: BookRecord) -> WriteResult: ...
    def get_book(self, book_id: str) -> BookRecord | None: ...
    def list_books(self) -> list[BookRecord]: ...
    def find_books(self, query: LibraryQuery) -> list[BookRecord]: ...


@runtime_checkable
class IntakeAdapter(Protocol):
    def receive(self): ...
    def reply(self, message) -> None: ...
